runtime: nodejs20
instance_class: F1
handlers:
  - url: /(.*\.(html|css|js|png|jpg|svg|json|ico))$
    static_files: \1
    upload: (.*\.(html|css|js|png|jpg|svg|json|ico))$
  - url: /.*
    static_files: index.html
    upload: index.html
